### ISSUE TITLE
Allow to extend set of parsers

### ISSUE THREAD

**Issue by prochac** [Showmax/env#9]
If I would like to add my custom parser I can't!

The `env.loader` has `AddParser` method what is unused and imposible to call from outside.
Because `env.loader` instance is unexported I can create it on my own.
The only instance of `env.loader` is created by `env.newLoader` function what is unexported as well.
And the instance is created in `env.Load` function what is the only thing what is exported from the package at all.

I don't see a point why that (env.loader#AddParser) code even exists if it's unused and unreachable.

**Comment by Hrubon** [comment]
> If I would like to add my custom parser I can't!
If you want to customize parsing logic for your own types, just implement the TextUnmarshaler interface on that type as stated in the documentation. If you want to implement parsing logic for types from third-party side, Just embed the third-party type into your own type and implement TextUnmarshaler on it.

> I don't see a point why that (env.loader#AddParser) code even exists if it's unused and unreachable.

**Comment by prochac** [comment]
ACK, I got confused from reading of the package code :) It feels like it's prepared for exposing, but the last step wasn't done.
